MI_Globals = {"Map Info ", 2.0, "Geert-Jan Uijtdewilligen", "List the currently active Archeology digsites and show the race (Dwarf/Fossil/Night Elf/..)", "Convert from World Coordinates to Map Coordinates and back"}
local mi = MI_Globals

-- Digsites by Continent
-- "Name", "Location", "Zone", "Type"

-- Eastern Kingdoms

DigsitesEasternKingdoms = {
{"Aerie Peak Digsite", "Aerie Peak", "Hinterlands", "Dwarf"}, 
{"Agol'watha Digsite", "Agol'watha", "Hinterlands", "Troll"}, 
{"Altar of Zul Digsite", "Altar of Zul", "Hinterlands", "Troll"}, 
{"Andorhal Fossil Bank", "West of Chillwind Camp", "Western Plaguelands", "Fossil"}, 
{"Bal'lal Ruins Digsite", "Bal'lal Ruins", "Northern Stranglethorn", "Troll"}, 
{"Balia'mah Digsite", "Balia'mah Ruins", "Northern Stranglethorn", "Troll"}, 
{"Dreadmaul Fossil Field", "Dreadmaul Post", "Blasted Lands", "Fossil"}, 
{"Dun Garok Digsite", "Dun Garok", "Hillsbrad Foothills", "Dwarf"}, 
{"Dunwald Ruins Digsite", "Dunwald Ruins", "Twilight Highlands", "Dwarf"}, 
{"Eastern Ruins of Thaurissan", "Ruins of Thaurissan", "Burning Steppes", "Dwarf"}, 
{"Eastern Zul'Kunda Digsite", "Ruins of Zul'Kunda", "Northern Stranglethorn", "Troll"}, 
{"Eastern Zul'Mamwe Digsite", "Ruins of Zul'Mamwe", "Northern Stranglethorn", "Troll"}, 
{"Felstone Fossil Field", "Felstone Field", "Western Plaguelands", "Fossil"}, 
{"Greenwarden's Fossil Bank", "Mosshide Fen", "Wetlands", "Fossil"}, 
{"Grimsilt DigSite", "Grimesilt Dig Site", "Searing Gorge", "Dwarf"}, 
{"Gurubashi Arena Digsite", "Gurubashi Arena", "Cape of Stranglethorn", "Troll"}, 
{"Hammertoe's Digsite", "Hammertoe's Digsite", "Badlands", "Dwarf"}, 
{"Humboldt Conflagration Digsite", "Humboldt Conflagration", "Twilight Highlands", "Dwarf"}, 
{"Infectis Scar Fossil Field", "Infectis Scar", "Eastern Plaguelands", "Fossil"}, 
{"Ironband's Excavation Site", "Ironband's Excavation Site", "Loch Modan", "Dwarf"}, 
{"Ironbeard's Tomb", "Ironbeard's Tomb", "Wetlands", "Dwarf"}, 
{"Jintha'Alor Lower City Digsite", "Jintha'Alor", "Hinterlands", "Troll"}, 
{"Jintha'Alor Upper City Digsite", "Jintha'Alor", "Hinterlands", "Troll"}, 
{"Lakeridge Highway Fossil Bank", "Lakeridge Highway", "Redridge Mountains", "Fossil"}, 
{"Misty Reed Fossil Bank", "Misty Reed Strand", "Swamp of Sorrows", "Fossil"}, 
{"Nek'mani Wellspring Digsite", "Nek'mani Wellspring", "Cape of Stranglethorn", "Troll"}, 
{"Northridge Fossil Field", "Northridge Lumber Camp", "Western Plaguelands", "Fossil"}, 
{"Plaguewood Digsite", "Plaguewood", "Eastern Plaguelands", "Nerubian"}, 
{"Pyrox Flats Digsite", "Pyrox Flats", "Searing Gorge", "Dwarf"}, 
{"Quel'Lithien Lodge Digsite", "Quel'Lithien Lodge", "Eastern Plaguelands", "Night Elf"}, 
{"Red Reaches Fossil Bank", "The Red Reaches", "Blasted Lands", "Fossil"}, 
{"Ruins of Aboraz", "Ruins of Aboraz", "Cape of Stranglethorn", "Troll"}, 
{"Ruins of Jubuwal", "Ruins of Jubuwal", "Cape of Stranglethorn", "Troll"}, 
{"Savage Coast Raptor Fields", "North of Grom'gol Base Camp", "Northern Stranglethorn", "Fossil"}, 
{"Shadra'Alor Digsite", "Shadra'Alor", "Hinterlands", "Troll"}, 
{"Southshore Fossil Field", "East of Tarren Mill/Southshore", "Hillsbrad Foothills", "Fossil"}, 
{"Sunken Temple Digsite", "Pool of Tears", "Swamp of Sorrows", "Troll"}, 
{"Terror Wing Fossil Field", "Terror Wing Path", "Burning Steppes", "Fossil"}, 
{"Terrorweb Tunnel Digsite", "Terrorweb Tunnel", "Eastern Plaguelands", "Nerubian"}, 
{"Thandol Span", "Thandol Span", "Wetlands", "Dwarf"}, 
{"Thoradin's Wall", "Thoradin's Wall", "Arathi Highlands", "Dwarf"}, 
{"Thundermar Ruins Digsite", "Thundermar Ruins", "Twilight Highlands", "Dwarf"}, 
{"Tomb of the Watchers Digsite", "Tomb of the Watchers", "Badlands", "Dwarf"}, 
{"Twilight Grove Digsite", "Twilight Grove", "Duskwood", "Night Elf"}, 
{"Uldaman Entrance Digsite", "The Maker's Terrace", "Badlands", "Dwarf"}, 
{"Vul'Gol Fossil Bank", "Vul'Gol Ogre Mound", "Duskwood", "Fossil"}, 
{"Western Ruins of Thaurissan", "Ruins of Thaurissan", "Burning Steppes", "Dwarf"}, 
{"Western Zul'Kunda Digsite", "Ruins of Zul'Kunda", "Northern Stranglethorn", "Troll"}, 
{"Western Zul'Mamwe Digsite", "Ruins of Zul'Mamwe", "Northern Stranglethorn", "Troll"}, 
{"Whelgar's Excavation Site", "Whelgar's Excavation Site", "Wetlands", "Dwarf"}, 
{"Witherbark Digsite", "Witherbark Village", "Arathi Highlands", "Troll"}, 
{"Ziata'jai Digsite", "North of Fort Livingston", "Northern Stranglethorn", "Troll"}, 
{"Zul'Mashar Digsite", "Zul'Mashar", "Eastern Plaguelands", "Troll"} 
}
local DigEK = DigsitesEasternKingdoms

--Kalimdor

DigsitesKalimdor = { 
{"Abyssal Sands Fossil Ridge", "Abyssal Sands", "Tanaris", "Fossil"}, 
{"Akhenet Fields Digsite", "Akhenet Fields", "Uldum", "Tol'vir"}, 
{"Bael Modan Digsite", "Bael Modan", "Southern Barrens", "Dwarf"}, 
{"Broken Commons Digsite", "Dire Maul", "Feralas", "Night Elf"}, 
{"Broken Pillar Digsite", "Broken Pillar", "Tanaris", "Troll"}, 
{"Constellas Digsite", "Ruins of Constellas", "Felwood", "Night Elf"}, 
{"Cursed Landing Digsite", "Cursed Landing", "Uldum", "Tol'vir"}, 
{"Darkmist Digsite", "Darkmist Ruins", "Feralas", "Night Elf"}, 
{"Dire Maul Digsite", "Dire Maul", "Feralas", "Night Elf"}, 
{"Dunemaul Fossil Ridge", "Southmoon Ruins", "Tanaris", "Fossil"}, 
{"Eastmoon Ruins Digsite", "Eastmoon Ruins", "Tanaris", "Troll"}, 
{"Ethel Rethor Digsite", "Slitherblade Shore", "Desolace", "Night Elf"}, 
{"Fields of Blood Fossil Bank", "Fields of Blood", "Southern Barrens", "Fossil"}, 
{"Forest Song Digsite", "Forest Song", "Ashenvale", "Night Elf"}, 
{"Frostwhisper Gorge Digsite", "Frostwhisper Gorge", "Winterspring", "Night Elf"}, 
{"Grove of Aessina Digsite", "Grove of Aessina", "Mount Hyjal", "Night Elf"}, 
{"Ironwood Digsite", "Irontree Woods", "Felwood", "Night Elf"}, 
{"Jaedenar Digsite", "Jaedenar", "Felwood", "Night Elf"}, 
{"Keset Pass Digsite", "Keset Pass", "Uldum", "Tol'vir"}, 
{"Khartut's Tomb Digsite", "Khartut's Tomb", "Uldum", "Tol'vir"}, 
{"Kodo Graveyard", "Kodo Graveyard", "Desolace", "Fossil"}, 
{"Lake Kel'Theril Digsite", "Lake Kel'Theril", "Winterspring", "Night Elf"}, 
{"Lower Lakkari Tar Pits", "Lakkari Tar Pits", "Un'Goro Crater", "Fossil"}, 
{"Mannoroc Coven Digsite", "Mannoroc Coven", "Desolace", "Night Elf"}, 
{"Marshlands Fossil Bank", "The Marshlands", "Un'Goro Crater", "Fossil"}, 
{"Morlos'Aran Digsite", "Morlos'Aran", "Felwood", "Night Elf"}, 
{"Nazj'vel Digsite", "Nazj'vel", "Darkshore", "Night Elf"}, 
{"Neferset Digsite", "Neferset City", "Uldum", "Tol'vir"}, 
{"Nightmare Scar Digsite", "Overgrowth", "Southern Barrens", "Night Elf"}, 
{"North Isildien Digsite", "Ruins of Isildien", "Feralas", "Night Elf"}, 
{"Obelisk of the Stars Digsite", "Obelisk of the Stars", "Uldum", "Tol'vir"}, 
{"Oneiros Digsite", "Dreamer's Rest", "Feralas", "Night Elf"}, 
{"Orsis Digsite", "Orsis", "Uldum", "Tol'vir"}, 
{"Owl Wing Thicket Digsite", "Owl Wing Thicket", "Winterspring", "Night Elf"}, 
{"Quagmire Fossil Field", "Quagmire", "Dustwallow Marsh", "Fossil"}, 
{"Ravenwind Digsite", "Ruins of Ravenwind", "Feralas", "Night Elf"}, 
{"River Delta Digsite", "Lost City of the Tol'vir", "Uldum", "Tol'vir"}, 
{"Ruins of Ahmtul Digsite", "Ruins of Ahmtul", "Uldum", "Tol'vir"}, 
{"Ruins of Ammon Digsite", "Ruins of Ammon", "Uldum", "Tol'vir"}, 
{"Ruins of Arkkoran", "Temple of Arkkoran", "Azshara", "Night Elf"}, 
{"Ruins of Eldarath", "Ruins of Eldarath", "Azshara", "Night Elf"}, 
{"Ruins of Eldre'Thar", "Ruins of Eldre'Thar", "Stonetalon Mountains", "Night Elf"}, 
{"Ruins of Khintaset Digsite", "Ruins of Khintaset", "Uldum", "Tol'vir"}, 
{"Ruins of Lar'donir Digsite", "Ruins of Lar'donir", "Mount Hyjal", "Night Elf"}, 
{"Ruins of Ordil'Aran", "The Ruins of Ordil'Aran", "Ashenvale", "Night Elf"}, 
{"Ruins of Stardust", "The Ruins of Stardust", "Ashenvale", "Night Elf"}, 
{"Sahket Wastes Digsite", "Sahket Wastes", "Uldum", "Tol'vir"}, 
{"Sanctuary of Malorne Digsite", "Sanctuary of Malorne", "Mount Hyjal", "Night Elf"}, 
{"Sargeron Digsite", "Sargeron", "Desolace", "Night Elf"}, 
{"Schnottz's Landing", "Schnottz's Landing", "Uldum", "Tol'vir"}, 
{"Scorched Plain Digsite", "The Scorched Plain", "Mount Hyjal", "Night Elf"}, 
{"Screaming Reaches Fossil Field", "Screaming Reaches", "Un'Goro Crater", "Fossil"}, 
{"Shrine of Goldrinn Digsite", "Shrine of Goldrinn", "Mount Hyjal", "Night Elf"}, 
{"Slitherblade Shore Digsite", "Slitherblade Shore", "Desolace", "Night Elf"}, 
{"Solarsal Digsite", "Ruins of Solarsal", "Feralas", "Night Elf"}, 
{"South Isildien Digsite", "Ruins of Isildien", "Feralas", "Night Elf"}, 
{"Southmoon Ruins Digsite", "Southmoon Ruins", "Tanaris", "Troll"}, 
{"Southwind Village Digsite", "Southwind Village", "Silithus", "Night Elf"}, 
{"Steps of Fate Digsite", "Steps of Fate", "Uldum", "Tol'vir"}, 
{"Stonetalon Peak", "Stonetalon Peak", "Stonetalon Mountains", "Night Elf"}, 
{"Temple of Uldum Digsite", "Temple of Uldum", "Uldum", "Tol'vir"}, 
{"Terror Run Fossil Field", "Terror Run", "Un'Goro Crater", "Fossil"}, 
{"Tombs of the Precursors Digsite", "Tombs of the Precursors", "Uldum", "Tol'vir"}, 
{"Unearthed Grounds", "Unearthed Grounds", "Stonetalon Mountains", "Fossil"}, 
{"Upper Lakkari Tar Pits", "Lakkari Tar Pits", "Un'Goro Crater", "Fossil"}, 
{"Valley of Bones", "Valley of Bones", "Desolace", "Fossil"}, 
{"Wyrmbog Fossil Field", "Wyrmbog", "Dustwallow Marsh", "Fossil"}, 
{"Zoram Strand Digsite", "Zoram Strand", "Ashenvale", "Night Elf"}, 
{"Zul'Farrak Digsite", "Sandsorrow Watch", "Tanaris", "Troll"} 
}
local DigKal = DigsitesKalimdor

--Outland

DigsitesOutland = {
{"Ancestral Grounds Digsite", "Ancestral Grounds", "Nagrand", "Orc"}, 
{"Arklon Ruins Digsite", "Arklon Ruins", "Netherstorm", "Draenei"}, 
{"Bleeding Hollow Ruins Digsite", "Bleeding Hollow Ruins", "Terokkar Forest", "Orc"}, 
{"Boha'mu Ruins Digsite", "Boha'mu Ruins", "Zangarmarsh", "Draenei"}, 
{"Bone Wastes Digsite", "Bone Wastes", "Terokkar Forest", "Draenei"}, 
{"Bonechewer Ruins Digsite", "Bonechewer Ruins", "Terokkar Forest", "Orc"}, 
{"Burning Blade Digsite", "Burning Blade Ruins", "Nagrand", "Orc"}, 
{"Coilskar Point Digsite", "Coilskar Point", "Shadowmoon Valley", "Draenei"}, 
{"Dragonmaw Fortress", "Dragonmaw Fortress", "Shadowmoon Valley", "Orc"}, 
{"East Auchindoun Digsite", "Auchindoun", "Terokkar Forest", "Draenei"}, 
{"Eclipse Point Digsite", "Eclipse Point", "Shadowmoon Valley", "Draenei"}, 
{"Gor'gaz Outpost Digsite", "Gor'gaz Outpost", "Hellfire Peninsula", "Orc"}, 
{"Grangol'var Village Digsite", "Grangol'var Village", "Terokkar Forest", "Orc"}, 
{"Halaa Digsite", "Halaa", "Nagrand", "Draenei"}, 
{"Hellfire Basin Digsite", "Hellfire Basin", "Hellfire Peninsula", "Orc"}, 
{"Hellfire Citadel Digsite", "Hellfire Citadel", "Hellfire Peninsula", "Orc"}, 
{"Illidari Point Digsite", "Illidari Point", "Shadowmoon Valley", "Draenei"}, 
{"Laughing Skull Digsite", "Laughing Skull Ruins", "Nagrand", "Orc"}, 
{"Ruins of Baa'ri Digsite", "Ruins of Baa'ri", "Shadowmoon Valley", "Draenei"}, 
{"Ruins of Enkaat Digsite", "Ruins of Enkaat", "Netherstorm", "Draenei"}, 
{"Ruins of Farahlon Digsite", "Ruins of Farahlon", "Netherstorm", "Draenei"}, 
{"Sha'naar Digsite", "Ruins of Sha'naar", "Hellfire Peninsula", "Draenei"}, 
{"Sunspring Post Digsite", "Sunspring Post", "Nagrand", "Orc"}, 
{"Tuurem Digsite", "Tuurem", "Terokkar Forest", "Draenei"}, 
{"Twin Spire Ruins Digsite", "Twin Spire Ruins", "Zangarmarsh", "Draenei"}, 
{"Warden's Cage Digsite", "Warden's Cage", "Shadowmoon Valley", "Orc"}, 
{"West Auchindoun Digsite", "Auchindoun", "Terokkar Forest", "Draenei"}, 
{"Zeth'Gor Digsite", "Zeth'Gor", "Hellfire Peninsula", "Orc"}
}
local DigOut = DigsitesOutland

--Northrend

DigsitesNorthrend = {
{"Altar of Quetz'lun Digsite", "Altar of Quetz'lun", "Zul'Drak", "Troll"}, 
{"Altar of Sseratus Digsite", "Altar of Sseratus", "Zul'Drak", "Troll"}, 
{"Baleheim Digsite", "Baleheim", "Howling Fjord", "Vrykul"}, 
{"Brunnhildar Village Digsite", "Brunnhildar Village", "The Storm Peaks", "Vrykul"}, 
{"Drakil'Jin Ruins Digsite", "Drakil'Jin Ruins", "Grizzly Hills", "Troll"}, 
{"En'kilah Digsite", "Temple City of En'kilah", "Borean Tundra", "Nerubian"}, 
{"Gjalerbron Digsite", "Gjalerbron", "Howling Fjord", "Vrykul"}, 
{"Halgrind Digsite", "Halgrind", "Howling Fjord", "Vrykul"}, 
{"Jotunheim Digsite", "Jotunheim", "Icecrown", "Vrykul"}, 
{"Kolramas Digsite", "Kolramas", "Zul'Drak", "Nerubian"}, 
{"Moonrest Gardens Digsite", "Moonrest Gardens", "Dragonblight", "Night Elf"}, 
{"Nifflevar Digsite", "Nifflevar", "Howling Fjord", "Vrykul"}, 
{"Njorndar Village Digsite", "Jotunheim", "Icecrown", "Vrykul"}, 
{"Pit of Fiends Digsite", "Pit of Fiends", "Icecrown", "Nerubian"}, 
{"Pit of Narjun Digsite", "The Pit of Narjun", "Dragonblight", "Nerubian"}, 
{"Riplash Ruins Digsite", "Riplash Ruins", "Borean Tundra", "Night Elf"}, 
{"Ruins of Shandaral Digsite", "Ruins of Shandaral", "Crystalsong Forest", "Night Elf"}, 
{"Sands of Nasam", "Sands of Nasam", "Borean Tundra", "Nerubian"}, 
{"Scourgeholme Digsite", "Scourgeholme", "Icecrown", "Nerubian"}, 
{"Shield Hill Digsite", "Shield Hill", "Howling Fjord", "Vrykul"}, 
{"Sifreldar Village Digsite", "Sifreldar Village", "The Storm Peaks", "Vrykul"}, 
{"Skorn Digsite", "Skorn", "Howling Fjord", "Vrykul"}, 
{"Talramas Digsite", "Talramas", "Borean Tundra", "Nerubian"}, 
{"Valkyrion Digsite", "Valkyrion", "The Storm Peaks", "Vrykul"}, 
{"Violet Stand Digsite", "Violet Stand", "Crystalsong Forest", "Night Elf"}, 
{"Voldrune Digsite", "Voldrune", "Grizzly Hills", "Vrykul"}, 
{"Wyrmskull Digsite", "Wyrmskull Village", "Howling Fjord", "Vrykul"}, 
{"Ymirheim Digsite", "Ymirheim", "Icecrown", "Vrykul"}, 
{"Zim'Rhuk Digsite", "Zim'Rhuk", "Zul'Drak", "Troll"}, 
{"Zol'Heb Digsite", "Zol'Heb", "Zul'Drak", "Troll"}
}
local DigNorth = DigsitesNorthrend

--Pandaria

DigsitesPandaria = { 
{"Amber Quarry Digsite", "Amber Quarry", "Dread Wastes", "Mantid"}, 
{"Chow Farmstead Digsite", "Chow Farmstead", "Kun-Lai Summit", "Pandaren"}, 
{"Den of Sorrow Digsite", "Den of Sorrow", "Jade Forest", "Pandaren"}, 
{"Destroyed Village Digsite", "Yinying Village", "Kun-Lai Summit", "Pandaren"}, 
{"East Snow Covered Hills Digsite", "Mount Neverest", "Kun-Lai Summit", "Mogu"}, 
{"East Sra'vess Digsite", "Sra'vess", "Townlong Steppes", "Mantid"}, 
{"East Summer Fields Digsite", "The Summer Fields", "Vale of Eternal Blossoms", "Mogu"}, 
{"Emperor's Approach Digsite", "The Emperor's Approach", "Vale of Eternal Blossoms", "Mogu"}, 
{"Emperor's Omen Digsite", "Emperor's Omen", "Jade Forest", "Pandaren"}, 
{"Fallsong Village Digsite", "Fallsong Village", "Krasarang Wilds", "Mogu"}, 
{"Fire Camp Osul Digsite", "Fire Camp Osul", "Townlong Steppes", "Mogu"}, 
{"Five Sisters Digsite", "The Five Sisters", "Vale of Eternal Blossoms", "Pandaren"}, 
{"Forest Heart Digsite", "Forest Heart", "Jade Forest", "Pandaren"}, 
{"Gate to Golden Valley Digsite", "Gate of the August Celestials", "Kun-Lai Summit", "Mogu"}, 
{"Gong of Hope Digsite", "The Gong of Hope", "Jade Forest", "Pandaren"}, 
{"Great Bridge Digsite", "Serpent's Heart", "Jade Forest", "Pandaren"}, 
{"Grumblepaw Ranch Digsite", "Muskpaw Ranch", "Kun-Lai Summit", "Pandaren"}, 
{"Hatred's Vice Digsite", "Hatred's Vice", "Townlong Steppes", "Mogu"}, 
{"Ikz'ka Ridge Digsite", "Ikz'ka Ridge (Sra'vess)", "Townlong Steppes", "Mantid"}, 
{"Jade Temple Grounds Digsite", "Jade Temple Grounds", "Jade Forest", "Pandaren"}, 
{"Kor'vess Digsite", "Kor'vess", "Dread Wastes", "Mantid"}, 
{"Krasarang Wilds Digsite", "Krasarang River/The Deepwild", "Krasarang Wilds", "Mogu"}, 
{"Kun-Lai Peak Digsite", "Seeker's Folly", "Kun-Lai Summit", "Pandaren"}, 
{"Kypari Vor Digsite", "Kypari Vor", "Dread Wastes", "Mantid"}, 
{"Kypari'ik Digsite", "Kypari Ik", "Dread Wastes", "Mantid"}, 
{"Kypari'zar Digsite", "Kypari Zar", "Dread Wastes", "Mantid"}, 
{"Kzzok Warcamp Digsite", "Kzzok Warcamp (Sra'vess)", "Townlong Steppes", "Mantid"}, 
{"Lake of Stars Digsite (north)", "Lake of Stars", "Dread Wastes", "Mantid"}, 
{"Lake of Stars Digsite (south)", "Lake of Stars", "Dread Wastes", "Mogu"}, 
{"Lost Dynasty Digsite", "The Krasari Ruins", "Krasarang Wilds", "Mogu"}, 
{"Mistfall Village Digsite", "Mistfall Village", "Vale of Eternal Blossoms", "Pandaren"}, 
{"Niuzao Temple Digsite", "Niuzao Temple", "Townlong Steppes", "Pandaren"}, 
{"North Fruited Fields Digsite", "The Heartland", "Valley of the Four Winds", "Pandaren"}, 
{"North Great Wall Digsite", "Stoneplow Fields", "Valley of the Four Winds", "Mogu"}, 
{"North Ruins of Dojan Digsite", "Ruins of Dojan", "Krasarang Wilds", "Mogu"}, 
{"North Ruins of Guo-Lai Digsite", "Ruins of Guo-Lai", "Vale of Eternal Blossoms", "Mogu"}, 
{"North Sik'vess Digsite", "Sik'vess", "Townlong Steppes", "Mantid"}, 
{"North Summer Fields Digsite", "The Summer Fields/Mogu'shan Palace", "Vale of Eternal Blossoms", "Mogu"}, 
{"North Temple of the Red Crane Digsite", "Temple of the Red Crane", "Krasarang Wilds", "Pandaren"}, 
{"Old Village Digsite", "Kun-Lai Pass/Binan Village", "Kun-Lai Summit", "Pandaren"}, 
{"Orchard Digsite", "The Arboretum", "Jade Forest", "Pandaren"}, 
{"Paoquan Hollow Digsite", "Paoquan Hollow", "Valley of the Four Winds", "Pandaren"}, 
{"Pools of Purity Digsite", "Pools of Purity", "Valley of the Four Winds", "Pandaren"}, 
{"Remote Village Digsite", "Zouchin Village", "Kun-Lai Summit", "Pandaren"}, 
{"Ruins of Gan Shi Digsite", "Ruins of Gan Shi", "Jade Forest", "Mogu"}, 
{"Ruins of Korja Digsite", "Ruins of Korja", "Krasarang Wilds", "Mogu"}, 
{"Setting Sun Garrison Digsite", "Setting Sun Garrison", "Vale of Eternal Blossoms", "Mogu"}, 
{"Shanze'Dao Digsite", "Shan'ze Dao", "Townlong Steppes", "Mogu"}, 
{"Shrine Meadow Digsite", "Shrine Meadow", "Jade Forest", "Pandaren"}, 
{"Shrine of the Dawn Digsite", "Shrine of the Dawn", "Jade Forest", "Pandaren"}, 
{"Sik'vess Digsite", "Sik'vess", "Townlong Steppes", "Mantid"}, 
{"Singing Marshes Digsite", "Singing Marshes", "Valley of the Four Winds", "Mogu"}, 
{"Small Gate Digsite", "The Ox Gate/Shado-Li Basin", "Kun-Lai Summit", "Pandaren"}, 
{"Snow Covered Hills Digsite", "Mount Neverest", "Kun-Lai Summit", "Mogu"}, 
{"South Fruited Fields Digsite", "The Heartland", "Valley of the Four Winds", "Pandaren"}, 
{"South Great Wall Digsite", "Dustback Gorge", "Valley of the Four Winds", "Mogu"}, 
{"South Orchard Digsite", "Nectarbreeze Orchard", "Jade Forest", "Pandaren"}, 
{"South Ruins of Dojan Digsite", "Ruins of Dojan", "Krasarang Wilds", "Mogu"}, 
{"South Ruins of Guo-Lai Digsite", "Ruins of Guo-Lai", "Vale of Eternal Blossoms", "Mogu"}, 
{"Sra'thik Digsite", "Niuzao Temple", "Townlong Steppes", "Pandaren"}, 
{"Sra'thik Swarmdock Digsite", "???", "Townlong Steppes", "Mantid"}, 
{"Terrace of Gurthan Digsite", "Terrace of Gurthan", "Dread Wastes", "Mogu"}, 
{"The Arboretum Digsite", "The Arboretum", "Jade Forest", "Pandaren"}, 
{"The Briny Muck Digsite", "The Briny Muck", "Dread Wastes", "Mantid"}, 
{"The Clutches of Shek'zeer Digsite", "The Clutches of Shek'zeer", "Dread Wastes", "Mantid"}, 
{"The Feeding Pits Digsite", "The Feeding Pits (Sra'vess)", "Townlong Steppes", "Mantid"}, 
{"The Spring Road Digsite", "The Spring Road", "Veiled Stair", "Mogu"}, 
{"The Underbough Digsite", "???", "Townlong Steppes", "Mantid"}, 
{"Thunderwood Digsite", "Camp Gormal", "Jade Forest", "Mogu"}, 
{"Tian Digsite", "Tian Monastery", "Jade Forest", "Pandaren"}, 
{"Tiger's Wood Digsite", "Tiger's Wood", "Jade Forest", "Pandaren"}, 
{"Torjari Pit Digsite", "Torjari Pit", "Valley of the Four Winds", "Mogu"}, 
{"Tu Shen Digsite", "Tu Shen Burial Ground", "Vale of Eternal Blossoms", "Mogu"}, 
{"Valley of Kings Digsite", "Valley of Emperors", "Kun-Lai Summit", "Mogu"}, 
{"Venomous Ledge Digsite", "Venomous Ledge", "Dread Wastes", "Mantid"}, 
{"Veridian Grove Digsite", "Veridian Grove", "Jade Forest", "Pandaren"}, 
{"West Old Village Digsite", "???", "Kun-Lai Summit", "Pandaren"}, 
{"West Ruins of Guo-Lai Digsite", "Ruins of Guo-Lai", "Vale of Eternal Blossoms", "Mogu"}, 
{"West Sik'vess Digsite", "Sik'vess", "Townlong Steppes", "Mantid"}, 
{"West Sra'vess Digsite", "Sra'vess", "Townlong Steppes", "Mantid"}, 
{"Winterbough Digsite", "Winterbough Glade/Jin Yang Road", "Vale of Eternal Blossoms", "Mogu"}, 
{"Writhingwood Digsite", "Forgotten Mire", "Dread Wastes", "Mogu"}, 
{"Zan'vess Digsite", "Zan'vess", "Dread Wastes", "Mantid"}, 
{"Zhu Province Digsite", "Zhu Province/Zhu's Watch", "Krasarang Wilds", "Pandaren"}
}
local DigPan = DigsitesPandaria

--Draenor

DigsitesDraenor = {
{"Ancestral Grounds Digsite", "Ancestral Grounds", "Nagrand", "Draenor Clans"}, 
{"Ango'rosh Digsite", "Ango'rosh Ruins", "Talador", "Ogre"}, 
{"Anguish Fortress Digsite", "Moonflower Valley", "Shadowmoon Valley", "Draenor Clans"}, 
{"Bloodmane Valley Digsite", "Bloodmane Valley", "Spires of Arak", "Arakkoa"}, 
{"Bloodmane Pridelands Digsite", "Windswept Terrace", "Spires of Arak", "Arakkoa"}, 
{"Burial Fields Digsite", "The Burial Fields", "Shadowmoon Valley", "Draenor Clans"}, 
{"Burning Plateau Digsite", "Elemental Plateau", "Nagrand", "Draenor Clans"}, 
{"Daggermaw Flows Digsite", "Frostwind Crag", "Frostfire Ridge", "Draenor Clans"}, 
{"Deadgrin Ruins Digsite", "Deadgrin", "Gorgrond", "Draenor Clans"}, 
{"Drowning Plateau Digsite", "Elemental Plateau", "Nagrand", "Draenor Clans"}, 
{"Duskfall Digsite", "Duskfall Island", "Talador", "Ogre"}, 
{"East Coldsnap Bluffs Digsite", "Coldsnap Bluffs", "Frostfire Ridge", "Draenor Clans"}, 
{"Forgotten Ogre Ruin Digsite", "Talador", "Talador", "Ogre"}, 
{"Frostboar Drifts Digsite", "Frostboar Drifts", "Frostfire Ridge", "Draenor Clans"}, 
{"Frozen Lake Digsite", "Forbidden Glacier", "Frostfire Ridge", "Draenor Clans"}, 
{"Gloomshade Digsite", "Gloomshade Grove", "Shadowmoon Valley", "Draenor Clans"}, 
{"Gordal Fortress Digsite", "Gordal Fortress", "Talador", "Ogre"}, 
{"Grom'Gar Digsite", "Grom'Gar", "Frostfire Ridge", "Draenor Clans"}, 
{"Highmaul Watchtower Digsite", "Nagrand", "Nagrand", "Ogre"}, 
{"Icewind Drifts Digsite", "Icewind Drifts", "Frostfire Ridge", "Draenor Clans"}, 
{"Kag'ah Digsite", "Spirit Woods", "Nagrand", "Draenor Clans"}, 
{"Mar'gok's Overwatch Digsite", "Mar'gok's Overwatch", "Nagrand", "Ogre"}, 
{"Overgrown Highmaul Road Digsite", "Nagrand", "Nagrand", "Ogre"}, 
{"Pinchwhistle Point Digsite", "Pinchwhistle Point", "Spires of Arak", "Arakkoa"}, 
{"Ring of Trials Sludge Digsite", "The Ring of Trials", "Nagrand", "Draenor Clans"}, 
{"Rumbling Plateau Digsite", "Elemental Plateau", "Nagrand", "Draenor Clans"}, 
{"Sethekk Hollow North Digsite", "Sethekk Hollow", "Spires of Arak", "Arakkoa"}, 
{"Sethekk Hollow South Digsite", "Sethekk Hollow", "Spires of Arak", "Arakkoa"}, 
{"Shimmering Moor Digsite", "Shimmer Moor", "Shadowmoon Valley", "Arakkoa"}, 
{"Southwind Cliffs Digsite", "Southwind Cliffs", "Frostfire Ridge", "Draenor Clans"}, 
{"Stonecrag Excavation Digsite", "Stonecrag Gorge", "Nagrand", "Ogre"}, 
{"The Broken Spine Digsite", "The Broken Spine", "Gorgrond", "Ogre"}, 
{"Umbrafen Digsite", "Umbrafen", "Shadowmoon Valley", "Ogre"}, 
{"Veil Akraz Digsite", "Veil Akraz", "Spires of Arak", "Arakkoa"}, 
{"Veil Shadar Digsite", "Veil Shadar", "Talador", "Arakkoa"}, 
{"Writhing Mire Digsite", "Writhing Mire", "Spires of Arak", "Ogre"}, 
{"Zangarra Digsite", "Zangarra", "Talador", "Ogre"}
}
local DigDra = DigsitesDraenor

--Broken Isles

DigsitesBrokenIsles = { 
{"Digsite: Aggramar's Vault", "Aggramar's Vault", "Stormheim", "Demonic"}, 
{"Digsite: Amberfall Mesa", "Amberfall Mesa", "Stormheim", "Demonic"}, 
{"Digsite: Andu'talah", "Andu'talah", "Val'sharah", "Highborne"}, 
{"Digsite: Anora Hollow", "Anora Hollow", "Suramar", "Demonic"}, 
{"Digsite: Black Rook Courtyard", "Black Rook Hold", "Val'sharah", "Highborne"}, 
{"Digsite: Bloodhunt Highland", "Bloodhunt Highland", "Highmountain", "Highmountain Tauren"}, 
{"Digsite: Bradensbrook", "Bradensbrook", "Val'sharah", "Demonic"}, 
{"Digsite: Citrine Bay", "Dreyrgrot", "Stormheim", "Demonic"}, 
{"Digsite: Cliffpaw Ridge", "Jotunnwood", "Stormheim", "Demonic"}, 
{"Digsite: Crimson Thicket", "Crimson Thicket", "Suramar", "Highborne / Demonic"},  
{"Digsite: Darkfeather Alley", "Darkfeather Valley", "Highmountain", "Highmountain Tauren"}, 
{"Digsite: Dragon's Falls", "Dragon's Falls", "Highmountain", "Highmountain Tauren"}, 
{"Digsite: Dreadroot Digsite", "Dreadroot", "Val'sharah", "Demonic"}, 
{"Digsite: Eastern Ambervale", "Ambervale", "Suramar", "Highborne"}, 
{"Digsite: Fallen Kings", "Field of Fallen Kings", "Stormheim", "Demonic"}, 
{"Digsite: Farondale", "Farondale", "Azsuna", "Demonic"}, 
{"Digsite: Feathermane Hunting Grounds", "Feathermane Hunting Grounds", "Suramar", "Demonic"}, 
{"Digsite: Felsoul Hold", "Felsoul Hold", "Suramar", "Demonic"}, 
{"Digsite: Fields of An'she", "Fields of An'she", "Highmountain", "Highmountain Tauren"}, 
{"Digsite: Garden of Elune", "Garden of Elune", "Azsuna", "Highborne"}, 
{"Digsite: Gates of the City", "Suramar", "Suramar", "Highborne"}, 
{"Digsite: Gates of Valor", "Gates of Valor", "Stormheim", "Demonic"}, 
{"Digsite: Kal'delar", "Kal'delar", "Val'sharah", "Highborne"}, 
{"Digsite: Koralune Estate", "Koralune Manor", "Suramar", "Highborne"}, 
{"Digsite: Legion Camp: Chaos", "Legion Camp: Chaos", "Azsuna", "Demonic"}, 
{"Digsite: Lightsong", "Lightsong", "Val'sharah", "Highborne"}, 
{"Digsite: Llothien", "Llothien", "Azsuna", "Highborne"}, 
{"Digsite: Llothien Highlands", "Llothien Highlands", "Azsuna", "Demonic"}, 
{"Digsite: Makrana", "Mak'rana", "Azsuna", "Demonic"}, 
{"Digsite: Meredil", "Meredil", "Suramar", "Highborne"}, 
{"Digsite: Moonwhisper Gulch", "Moonwhisper Gulch", "Suramar", "Highborne"}, 
{"Digsite: Northern Moonfall Retreat", "Moonfall Retreat", "Suramar", "Highborne"}, 
{"Digsite: Northern Snowblind Mesa", "Snowblind Mesa", "Highmountain", "Highmountain Tauren"}, 
{"Digsite: Northern Watcher Isle", "Isle of the Watchers", "Azsuna", "Demonic"}, 
{"Digsite: Old Coast Path", "Old Coast Path", "Azsuna", "Highborne"}, 
{"Digsite: Pinerock Basin", "Pinerock Basin", "Highmountain", "Highmountain Tauren"}, 
{"Digsite: Prowler's Scratch", "North of Thunder Totem", "Highmountain", "Highmountain Tauren"}, 
{"Digsite: Rhut'van Passage", "Rhut'van Passage", "Azsuna", "Demonic"}, 
{"Digsite: Ruins of Zarkhenar", "Ley-Ruins of Zarkhenar", "Azsuna", "Highborne"}, 
{"Digsite: Screeching Bend", "Screeching Crag", "Highmountain", "Highmountain Tauren"}, 
{"Digsite: Shala'nir", "Shala'nir", "Val'sharah", "Demonic"}, 
{"Digsite: Skold-Ashil", "Skold-Ashil", "Stormheim", "Demonic"}, 
{"Digsite: Sky Sepulcher", "Sepulcher of the Sky", "Highmountain", "Highmountain Tauren"}, 
{"Digsite: Southern Helmouth Shallows", "Helmouth Shallows", "Stormheim", "Demonic"}, 
{"Digsite: Southern Snowblind Mesa", "Snowblind Mesa", "Highmountain", "Highmountain Tauren"}, 
{"Digsite: Southern Suramar", "Seaspray Cliffs", "Suramar", "Demonic"}, 
{"Digsite: Southern Wash", "Southern Wash", "Val'sharah", "Highborne"}, 
{"Digsite: Southern Watcher Isle (copy)", "Isle of the Watchers", "Azsuna", "Demonic"}, 
{"Digsite: Storm's Reach Digsite", "Storm's Reach", "Stormheim", "Demonic"}, 
{"Digsite: Stormdrake Peak Digsite", "Stormtorn Foothills", "Stormheim", "Demonic"}, 
{"Digsite: Sundered Shoals Digsite", "Sundered Shoals", "Suramar", "Demonic"}, 
{"Digsite: Sundersong Glade", "Sundersong Glade", "Val'sharah", "Highborne"}, 
{"Digsite: Temple of a Thousand Lights", "Temple of a Thousand Lights", "Azsuna", "Highborne"}, 
{"Digsite: Thas'talah Digsite", "Field of Dreamers", "Val'sharah", "Demonic"}, 
{"Digsite: The Crescent Vale Digsite", "Howling Dale", "Val'sharah", "Demonic"}, 
{"Digsite: The Haglands Digsite", "The Haglands", "Highmountain", "Highmountain Tauren"}, 
{"Digsite: The Ruined Sancum Digsite", "The Ruined Sanctum", "Azsuna", "Highborne"}, 
{"Digsite: The Tidal Marsh Digsite", "Alluvanon's Delta", "Azsuna", "Highborne"}, 
{"Digsite: The Witchwood Digsite", "The Witchwood", "Highmountain", "Highmountain Tauren"}, 
{"Digsite: Timeworn Strand Digsite", "Timeworn Strand", "Azsuna", "Demonic"}, 
{"Digsite: Warden's Bluff Digsite", "Whisperwind Citadel", "Stormheim", "Demonic"}, 
{"Digsite: Whitewater Wash Digsite", "Whitewater Wash", "Highmountain", "Highmountain Tauren"}, 
{"Digsite: Wildwood Digsite", "The Wildwood", "Val'sharah", "Demonic"}, 
{"Digsite: Wretched Hollow Digsite", "Wretched Hollow", "Val'sharah", "Demonic"}
}
local DigBro = DigsitesBrokenIsles

--Kul Tiras

DigsitesKulTiras = {
{"Digsite: Arom's Crossing", "Arom's Crossing / Highroad Pass / South of Arom's Crossing", "Drustvar", "Drust"}, 
{"Digsite: Brackish Coast", "Brackish Coast", "Drustvar", "Drust"}, 
{"Digsite: Briny Flats", "Briny Flats", "Stormsong Valley", "Drust"}, 
{"Digsite: Brokenbough Roost", "Splinterbark Roost", "Tiragarde Sound", "Drust"}, 
{"Digsite: Corlain", "Corlain", "Drustvar", "Drust"},
{"Digsite: Crimson Forest", "Crimson Forest", "Drustvar", "Drust"}, 
{"Digsite: Dire Hills", "Windshorn Hills", "Stormsong Valley", "Drust"}, 
{"Digsite: Drowned Lands", "Drowned Lands", "Stormsong Valley", "Drust"}, 
{"Digsite: Goldfield Farmstead", "Goldfield Farmstead / Amber Waves", "Stormsong Valley", "Drust"}, 
{"Digsite: Hunter's Run", "Hunter's Run", "Drustvar", "Drust"}, 
{"Digsite: Iceveil Glacier", "Iceveil Glacier", "Drustvar", "Drust"}, 
{"Digsite: Millstone Hills", "Beryl Meadow", "Stormsong Valley", "Drust"}, 
{"Digsite: Placid Springs", "Placid Spring", "Tiragarde Sound", "Drust"}, 
{"Digsite: Roaming Hills", "Scalespine Hill", "Stormsong Valley", "Drust"}, 
{"Digsite: Rockslip Woodlands", "<Southwest of Norwington Estate", "Tiragarde Sound", "Drust"}, 
{"Digsite: Stagheart Cliffs", "Stagheart Wash", "Tiragarde Sound", "Drust"}, 
{"Digsite: Valley View", "Evergreen Grove", "Tiragarde Sound", "Drust"}, 
{"Digsite: Vigil Hill", "Vigil Hill", "Tiragarde Sound", "Drust"}, 
{"Digsite: Whitegrove Chapel", "Whitegrove Chapel", "Drustvar", "Drust"}, 
{"Digsite: Windwhisper Summit", "Tidebreak Summit / East of Windfall Cavern", "Stormsong Valley", "Drust"}
}
local DigKul = DigsitesKulTiras

--Zandalar

DigsitesZandalar = {
{"Digsite: Arid Basin", "Arid Basin", "Vol'dun", "Zandalari"}, 
{"Digsite: Atal'Gral", "Atal'Gral", "Zuldazar", "Zandalari"}, 
{"Digsite: Dreadpearl Shallows", "Dreadpearl Shallows", "Zuldazar", "Zandalari"}, 
{"Digsite: Natha'vor", "Natha'vor", "Nazmir", "Zandalari"}, 
{"Digsite: Old Merchant Road", "Old Merchant Road / Garden of the Loa", "Zuldazar", "Zandalari"}, 
{"Digsite: Plains of Tojek", "Plains of Tojek", "Nazmir", "Zandalari"}, 
{"Digsite: Razorjaw River", "Razorjaw River", "Nazmir", "Zandalari"}, 
{"Digsite: Savagelands", "Savagelands", "Zuldazar", "Zandalari"}, 
{"Digsite: Terrace of Sorrows", "Terrace of Sorrows", "Nazmir", "Zandalari"}, 
{"Digsite: The Cracked Coast", "Cracked Coast", "Vol'dun", "Zandalari"}, 
{"Digsite: The Eternal Spring", "Eternal Spring", "Vol'dun", "Zandalari"}, 
{"Digsite: The Rivermarsh", "Rivermarsh", "Zuldazar", "Zandalari"}, 
{"Digsite: Tusk Isle", "Tusk Isle", "Zuldazar", "Zandalari"}, 
{"Digsite: Upper Frogmarsh", "Upper Frogmarsh / Krag'wa's Shore", "Nazmir", "Zandalari"}, 
{"Digsite: Verdant Plateau", "Verdant Plateau", "Vol'dun", "Zandalari"}, 
{"Digsite: Whistlebloom Oasis", "Whistlebloom Oasis", "Vol'dun", "Zandalari"}, 
{"Digsite: Xal'vor", "Xal'vor", "Nazmir", "Zandalari"}, 
{"Digsite: Zeb'ahari", "Zeb'ahari", "Zuldazar", "Zandalari"}
}
local DigZan = DigsitesZandalar